import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";
import Header from "@/components/Header";

const integralCFRegular = localFont({
  src: "../fonts/IntegralCF-Regular.woff",
  variable: "--font-IntegralCF-regular",
});

const satoshiRegular = localFont({
  src: "../fonts/Satoshi-Regular.woff",
  variable: "--font-Satoshi-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          <main
            className={`${integralCFRegular.variable} ${satoshiRegular.variable} antialiased`}
          >
            <Header />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
